### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by daniel** [jxnblk/stepkit#19]
Cool project! I can't get it to work locally though :( When I load the page I get this error:
Uncaught TypeError: Cannot read property 'name' of undefined (app.js:21107)

**Comment by daniel** [comment]
I got it to work now! Somehow I got a slash at the end of the url, like this:
http://localhost:8000/?tempo=96&currentKit=1&currentBank=2/

**Comment by jxnblk** [comment]
Thanks. Not sure what's happening but this app definitely needs some better fault tolerance.
